services:
  svia:
    image: svia-diif-beac:test
    container_name: svia_app
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
